runtime: go116

service: default

env_variables:
  DB_PATH: ./data/eadditives.sqlite3

handlers:
- url: /
  static_files: www/build/index.html
  upload: www/build/index.html

- url: /api(.*)
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /(.*)
  static_files: www/build/\1
  upload: www/build/(.*)