runtime: go116

service: default

env_variables:
  EAD_LISTEN_PORT: 8080

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /api(.*)
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)