# see https://github.com/GoogleCloudPlatform/cloud-build-samples/tree/main/golang-sample
steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west3-docker.pkg.dev/$PROJECT_ID/eadditives/myimage:$SHORT_SHA', '.']
  
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/eadditives/myimage:$SHORT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'DB_PATH=./data/eadditives.sqlite3'
    args: ['run', 'deploy', 'eadditives-${SHORT_SHA}', 
           '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/eadditives/myimage:$SHORT_SHA', 
           '--region', 'europe-west3', '--platform', 'managed']

# Store images in Google Artifact Registry
# images:
#   - $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/myimage:$SHORT_SHA